[package]
name = "mpc_transactions"
version = "1.0.0"
edition = "2021"

[dependencies]
ink_lang = "4.0"
ink_storage = "4.0"
bls12_381 = "0.7.0"
sha2 = "0.10.0"
rand_core = "0.6.4"
scale-info = { version = "2.0", features = ["derive"] }
